<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>CleanApiStarter.Application.UnitTests</RootNamespace>
        <PackageId>CleanApiStarter.Application.UnitTests</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\CleanApiStarter.Application\CleanApiStarter.Application.csproj" />
    </ItemGroup>

</Project>
