<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CleanApiStarter.AppHost</RootNamespace>
    <AssemblyName>CleanApiStarter.AppHost</AssemblyName>
    <UserSecretsId>clean-api-starter-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanApiStarter.Api\CleanApiStarter.Api.csproj" />
  </ItemGroup>

</Project>
