<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>CleanApiStarter.AppHost</RootNamespace>
        <AssemblyName>CleanApiStarter.AppHost</AssemblyName>
        <UserSecretsId>clean-api-starter-apphost</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack"/>
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CleanApiStarter.Api\CleanApiStarter.Api.csproj"/>
    </ItemGroup>

</Project>
