@CleanApiStarter_Api_HostAddress = http://localhost:5219

GET {{CleanApiStarter_Api_HostAddress}}/api/words
Accept: application/json

###

POST {{CleanApiStarter_Api_HostAddress}}/api/words
Content-Type: application/json

{
  "text": "observable",
  "meaning": "Able to be noticed, measured, or monitored.",
  "synonyms": ["visible", "measurable"],
  "usageExample": "OpenTelemetry makes API behavior observable."
}

###
