@CleanApiStarter_Api_HostAddress = https://localhost:7285

GET {{CleanApiStarter_Api_HostAddress}}/api/words
Accept: application/json
X-Api-Version: 1.0

###

POST {{CleanApiStarter_Api_HostAddress}}/api/words
Content-Type: application/json
X-Api-Version: 1.0

{
  "text": "observable",
  "meaning": "Able to be noticed, measured, or monitored.",
  "synonyms": ["visible", "measurable"],
  "usageExample": "OpenTelemetry makes API behavior observable."
}

###

GET {{CleanApiStarter_Api_HostAddress}}/api/words
Accept: application/json
X-Api-Version: 2.0

###
