<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>CleanApiStarter.Api</RootNamespace>
    <AssemblyName>CleanApiStarter.Api</AssemblyName>
    <UserSecretsId>clean-api-starter</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanApiStarter.Application\CleanApiStarter.Application.csproj" />
    <ProjectReference Include="..\CleanApiStarter.Infrastructure\CleanApiStarter.Infrastructure.csproj" />
    <ProjectReference Include="..\CleanApiStarter.AspNetCore\CleanApiStarter.AspNetCore.csproj" />
  </ItemGroup>

</Project>
