<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CleanApiStarter.Tests</RootNamespace>
        <PackageId>CleanApiStarter.Tests</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture.AutoNSubstitute" PrivateAssets="all" />
        <PackageReference Include="AutoFixture.Xunit3" PrivateAssets="all" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="Testcontainers.PostgreSql" />
    </ItemGroup>

</Project>
