<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>CleanApiStarter.Api.IntegrationTests</RootNamespace>
        <PackageId>CleanApiStarter.Api.IntegrationTests</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
        <PackageReference Include="Shouldly" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CleanApiStarter.Api\CleanApiStarter.Api.csproj" />
        <ProjectReference Include="..\CleanApiStarter.Tests\CleanApiStarter.Tests.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.Testing.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
