name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore CleanApiStarter.slnx

      - name: Format
        run: dotnet format CleanApiStarter.slnx --verify-no-changes --no-restore

      - name: Build
        run: dotnet build CleanApiStarter.slnx --no-restore --configuration Release /nr:false -v:minimal

      - name: Test
        run: dotnet test CleanApiStarter.slnx --no-build --configuration Release /nr:false -v:minimal
